# docker-compose.yml

version: "3.9"
services:
  node1:
    build: .
    container_name: node1
    ports:
      - "8081:8080"
    environment:
      - PEERS=http://node2:8080,http://node3:8080
    networks:
      - blockchain-network

  node2:
    build: .
    container_name: node2
    ports:
      - "8082:8080"
    environment:
      - PEERS=http://node1:8080,http://node3:8080
    networks:
      - blockchain-network

  node3:
    build: .
    container_name: node3
    ports:
      - "8083:8080"
    environment:
      - PEERS=http://node1:8080,http://node2:8080
    networks:
      - blockchain-network

networks:
  blockchain-network:
    driver: bridge
