version: "3.9"
services:
  node1:
    build: .
    container_name: node1
    ports:
      - "8081:8080"
    environment:
      - NODE_PORT=8080
  node2:
    build: .
    container_name: node2
    ports:
      - "8082:8080"
    environment:
      - NODE_PORT=8080
  node3:
    build: .
    container_name: node3
    ports:
      - "8083:8080"
    environment:
      - NODE_PORT=8080
